# Generated by Django 4.1.5 on 2023-01-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0007_carrito_carritoitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carrito", old_name="total_medicity", new_name="total_fybeca",
        ),
    ]
