# Generated by Django 4.1.5 on 2023-01-31 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0008_rename_total_medicity_carrito_total_fybeca"),
    ]

    operations = [
        migrations.RemoveField(model_name="basketitem", name="basket",),
        migrations.RemoveField(model_name="basketitem", name="product",),
        migrations.DeleteModel(name="Basket",),
        migrations.DeleteModel(name="BasketItem",),
    ]
