# Generated by Django 4.1.5 on 2023-01-22 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_auto_20191114_2202"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, default="imagen_por_defecto.png", upload_to=""
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField()),
                (
                    "url_farmacias_economicas",
                    models.CharField(db_index=True, max_length=400),
                ),
                ("url_medicity", models.CharField(db_index=True, max_length=400)),
                ("url_pharmacys", models.CharField(db_index=True, max_length=400)),
                (
                    "precio_farmacias_economicas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "precio_medicity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "precio_pharmacys",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, default="imagen_por_defecto.png", upload_to=""
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categoria",
                    ),
                ),
            ],
            options={"ordering": ("nombre",), "index_together": {("id", "slug")},},
        ),
    ]
