# Generated by Django 4.1.5 on 2023-01-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_categoria_producto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto", old_name="precio_medicity", new_name="precio_fybeca",
        ),
        migrations.AddField(
            model_name="producto",
            name="compuesto",
            field=models.CharField(db_index=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
