# Generated by Django 4.1.5 on 2023-01-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_rename_precio_medicity_producto_precio_fybeca_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto", old_name="url_medicity", new_name="url_fybeca",
        ),
    ]
