# Generated by Django 4.1.5 on 2023-01-31 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0009_remove_basketitem_basket_remove_basketitem_product_and_more"),
        ("products", "0011_rename_url_medicity_producto_url_fybeca"),
    ]

    operations = [
        migrations.AlterIndexTogether(name="product", index_together=None,),
        migrations.RemoveField(model_name="product", name="category",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Product",),
    ]
